// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "compute_output.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic compute_output::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic compute_output::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> compute_output::ap_ST_fsm_state1 = "1";
const sc_lv<7> compute_output::ap_ST_fsm_state2 = "10";
const sc_lv<7> compute_output::ap_ST_fsm_state3 = "100";
const sc_lv<7> compute_output::ap_ST_fsm_state4 = "1000";
const sc_lv<7> compute_output::ap_ST_fsm_state5 = "10000";
const sc_lv<7> compute_output::ap_ST_fsm_state6 = "100000";
const sc_lv<7> compute_output::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> compute_output::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> compute_output::ap_const_lv1_0 = "0";
const sc_lv<3> compute_output::ap_const_lv3_0 = "000";
const sc_lv<2> compute_output::ap_const_lv2_0 = "00";
const sc_lv<4> compute_output::ap_const_lv4_0 = "0000";
const sc_lv<16> compute_output::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> compute_output::ap_const_lv32_5 = "101";
const sc_lv<32> compute_output::ap_const_lv32_6 = "110";
const sc_lv<7> compute_output::ap_const_lv7_0 = "0000000";
const sc_lv<32> compute_output::ap_const_lv32_3 = "11";
const sc_lv<32> compute_output::ap_const_lv32_4 = "100";
const sc_lv<32> compute_output::ap_const_lv32_1 = "1";
const sc_lv<32> compute_output::ap_const_lv32_2 = "10";
const sc_lv<7> compute_output::ap_const_lv7_10 = "10000";
const sc_lv<1> compute_output::ap_const_lv1_1 = "1";
const sc_lv<64> compute_output::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const bool compute_output::ap_const_boolean_1 = true;

compute_output::compute_output(sc_module_name name) : sc_module(name), mVcdFile(0) {
    wt_buff_V_U = new compute_output_wtg8j("wt_buff_V_U");
    wt_buff_V_U->clk(ap_clk);
    wt_buff_V_U->reset(ap_rst);
    wt_buff_V_U->address0(wt_buff_V_address0);
    wt_buff_V_U->ce0(wt_buff_V_ce0);
    wt_buff_V_U->we0(wt_buff_V_we0);
    wt_buff_V_U->d0(grp_load_weight_fu_714_wt_buff_V_d0);
    wt_buff_V_U->q0(wt_buff_V_q0);
    wt_buff_V_U->address1(grp_compute4_fu_624_wt_buff_V_address1);
    wt_buff_V_U->ce1(wt_buff_V_ce1);
    wt_buff_V_U->q1(wt_buff_V_q1);
    fm_out_buff_V_U = new compute_output_fmhbi("fm_out_buff_V_U");
    fm_out_buff_V_U->clk(ap_clk);
    fm_out_buff_V_U->reset(ap_rst);
    fm_out_buff_V_U->address0(fm_out_buff_V_address0);
    fm_out_buff_V_U->ce0(fm_out_buff_V_ce0);
    fm_out_buff_V_U->we0(fm_out_buff_V_we0);
    fm_out_buff_V_U->d0(grp_compute4_fu_624_fm_out_buff_V_d0);
    fm_out_buff_V_U->q0(fm_out_buff_V_q0);
    fm_out_buff_V_U->address1(grp_compute4_fu_624_fm_out_buff_V_address1);
    fm_out_buff_V_U->ce1(fm_out_buff_V_ce1);
    fm_out_buff_V_U->we1(fm_out_buff_V_we1);
    fm_out_buff_V_U->d1(grp_compute4_fu_624_fm_out_buff_V_d1);
    fm_out_buff_V_U->q1(fm_out_buff_V_q1);
    grp_compute4_fu_624 = new compute4("grp_compute4_fu_624");
    grp_compute4_fu_624->ap_clk(ap_clk);
    grp_compute4_fu_624->ap_rst(ap_rst);
    grp_compute4_fu_624->ap_start(grp_compute4_fu_624_ap_start);
    grp_compute4_fu_624->ap_done(grp_compute4_fu_624_ap_done);
    grp_compute4_fu_624->ap_idle(grp_compute4_fu_624_ap_idle);
    grp_compute4_fu_624->ap_ready(grp_compute4_fu_624_ap_ready);
    grp_compute4_fu_624->fm_in_buff_0_V_address0(grp_compute4_fu_624_fm_in_buff_0_V_address0);
    grp_compute4_fu_624->fm_in_buff_0_V_ce0(grp_compute4_fu_624_fm_in_buff_0_V_ce0);
    grp_compute4_fu_624->fm_in_buff_0_V_q0(fm_in_buff_0_V_q0);
    grp_compute4_fu_624->fm_in_buff_1_V_address0(grp_compute4_fu_624_fm_in_buff_1_V_address0);
    grp_compute4_fu_624->fm_in_buff_1_V_ce0(grp_compute4_fu_624_fm_in_buff_1_V_ce0);
    grp_compute4_fu_624->fm_in_buff_1_V_q0(fm_in_buff_1_V_q0);
    grp_compute4_fu_624->fm_in_buff_2_V_address0(grp_compute4_fu_624_fm_in_buff_2_V_address0);
    grp_compute4_fu_624->fm_in_buff_2_V_ce0(grp_compute4_fu_624_fm_in_buff_2_V_ce0);
    grp_compute4_fu_624->fm_in_buff_2_V_q0(fm_in_buff_2_V_q0);
    grp_compute4_fu_624->wt_buff_V_address0(grp_compute4_fu_624_wt_buff_V_address0);
    grp_compute4_fu_624->wt_buff_V_ce0(grp_compute4_fu_624_wt_buff_V_ce0);
    grp_compute4_fu_624->wt_buff_V_q0(wt_buff_V_q0);
    grp_compute4_fu_624->wt_buff_V_address1(grp_compute4_fu_624_wt_buff_V_address1);
    grp_compute4_fu_624->wt_buff_V_ce1(grp_compute4_fu_624_wt_buff_V_ce1);
    grp_compute4_fu_624->wt_buff_V_q1(wt_buff_V_q1);
    grp_compute4_fu_624->bias_buff_0_V_read(bias_buff_0_V_read);
    grp_compute4_fu_624->bias_buff_1_V_read(bias_buff_1_V_read);
    grp_compute4_fu_624->bias_buff_2_V_read(bias_buff_2_V_read);
    grp_compute4_fu_624->bias_buff_3_V_read(bias_buff_3_V_read);
    grp_compute4_fu_624->bias_buff_4_V_read(bias_buff_4_V_read);
    grp_compute4_fu_624->bias_buff_5_V_read(bias_buff_5_V_read);
    grp_compute4_fu_624->bias_buff_6_V_read(bias_buff_6_V_read);
    grp_compute4_fu_624->bias_buff_7_V_read(bias_buff_7_V_read);
    grp_compute4_fu_624->bias_buff_8_V_read(bias_buff_8_V_read);
    grp_compute4_fu_624->bias_buff_9_V_read(bias_buff_9_V_read);
    grp_compute4_fu_624->bias_buff_10_V_read(bias_buff_10_V_read);
    grp_compute4_fu_624->bias_buff_11_V_read(bias_buff_11_V_read);
    grp_compute4_fu_624->bias_buff_12_V_read(bias_buff_12_V_read);
    grp_compute4_fu_624->bias_buff_13_V_read(bias_buff_13_V_read);
    grp_compute4_fu_624->bias_buff_14_V_read(bias_buff_14_V_read);
    grp_compute4_fu_624->bias_buff_15_V_read(bias_buff_15_V_read);
    grp_compute4_fu_624->bias_buff_16_V_read(bias_buff_16_V_read);
    grp_compute4_fu_624->bias_buff_17_V_read(bias_buff_17_V_read);
    grp_compute4_fu_624->bias_buff_18_V_read(bias_buff_18_V_read);
    grp_compute4_fu_624->bias_buff_19_V_read(bias_buff_19_V_read);
    grp_compute4_fu_624->bias_buff_20_V_read(bias_buff_20_V_read);
    grp_compute4_fu_624->bias_buff_21_V_read(bias_buff_21_V_read);
    grp_compute4_fu_624->bias_buff_22_V_read(bias_buff_22_V_read);
    grp_compute4_fu_624->bias_buff_23_V_read(bias_buff_23_V_read);
    grp_compute4_fu_624->bias_buff_24_V_read(bias_buff_24_V_read);
    grp_compute4_fu_624->bias_buff_25_V_read(bias_buff_25_V_read);
    grp_compute4_fu_624->bias_buff_26_V_read(bias_buff_26_V_read);
    grp_compute4_fu_624->bias_buff_27_V_read(bias_buff_27_V_read);
    grp_compute4_fu_624->bias_buff_28_V_read(bias_buff_28_V_read);
    grp_compute4_fu_624->bias_buff_29_V_read(bias_buff_29_V_read);
    grp_compute4_fu_624->bias_buff_30_V_read(bias_buff_30_V_read);
    grp_compute4_fu_624->bias_buff_31_V_read(bias_buff_31_V_read);
    grp_compute4_fu_624->bias_buff_32_V_read(bias_buff_32_V_read);
    grp_compute4_fu_624->bias_buff_33_V_read(bias_buff_33_V_read);
    grp_compute4_fu_624->bias_buff_34_V_read(bias_buff_34_V_read);
    grp_compute4_fu_624->bias_buff_35_V_read(bias_buff_35_V_read);
    grp_compute4_fu_624->bias_buff_36_V_read(bias_buff_36_V_read);
    grp_compute4_fu_624->bias_buff_37_V_read(bias_buff_37_V_read);
    grp_compute4_fu_624->bias_buff_38_V_read(bias_buff_38_V_read);
    grp_compute4_fu_624->bias_buff_39_V_read(bias_buff_39_V_read);
    grp_compute4_fu_624->bias_buff_40_V_read(bias_buff_40_V_read);
    grp_compute4_fu_624->bias_buff_41_V_read(bias_buff_41_V_read);
    grp_compute4_fu_624->bias_buff_42_V_read(bias_buff_42_V_read);
    grp_compute4_fu_624->bias_buff_43_V_read(bias_buff_43_V_read);
    grp_compute4_fu_624->bias_buff_44_V_read(bias_buff_44_V_read);
    grp_compute4_fu_624->bias_buff_45_V_read(bias_buff_45_V_read);
    grp_compute4_fu_624->bias_buff_46_V_read(bias_buff_46_V_read);
    grp_compute4_fu_624->bias_buff_47_V_read(bias_buff_47_V_read);
    grp_compute4_fu_624->bias_buff_48_V_read(bias_buff_48_V_read);
    grp_compute4_fu_624->bias_buff_49_V_read(bias_buff_49_V_read);
    grp_compute4_fu_624->bias_buff_50_V_read(bias_buff_50_V_read);
    grp_compute4_fu_624->bias_buff_51_V_read(bias_buff_51_V_read);
    grp_compute4_fu_624->bias_buff_52_V_read(bias_buff_52_V_read);
    grp_compute4_fu_624->bias_buff_53_V_read(bias_buff_53_V_read);
    grp_compute4_fu_624->bias_buff_54_V_read(bias_buff_54_V_read);
    grp_compute4_fu_624->bias_buff_55_V_read(bias_buff_55_V_read);
    grp_compute4_fu_624->bias_buff_56_V_read(bias_buff_56_V_read);
    grp_compute4_fu_624->bias_buff_57_V_read(bias_buff_57_V_read);
    grp_compute4_fu_624->bias_buff_58_V_read(bias_buff_58_V_read);
    grp_compute4_fu_624->bias_buff_59_V_read(bias_buff_59_V_read);
    grp_compute4_fu_624->bias_buff_60_V_read(bias_buff_60_V_read);
    grp_compute4_fu_624->bias_buff_61_V_read(bias_buff_61_V_read);
    grp_compute4_fu_624->bias_buff_62_V_read(bias_buff_62_V_read);
    grp_compute4_fu_624->bias_buff_63_V_read(bias_buff_63_V_read);
    grp_compute4_fu_624->bias_buff_V_offset(ch_0_reg_612);
    grp_compute4_fu_624->fm_out_buff_V_address0(grp_compute4_fu_624_fm_out_buff_V_address0);
    grp_compute4_fu_624->fm_out_buff_V_ce0(grp_compute4_fu_624_fm_out_buff_V_ce0);
    grp_compute4_fu_624->fm_out_buff_V_we0(grp_compute4_fu_624_fm_out_buff_V_we0);
    grp_compute4_fu_624->fm_out_buff_V_d0(grp_compute4_fu_624_fm_out_buff_V_d0);
    grp_compute4_fu_624->fm_out_buff_V_q0(fm_out_buff_V_q0);
    grp_compute4_fu_624->fm_out_buff_V_address1(grp_compute4_fu_624_fm_out_buff_V_address1);
    grp_compute4_fu_624->fm_out_buff_V_ce1(grp_compute4_fu_624_fm_out_buff_V_ce1);
    grp_compute4_fu_624->fm_out_buff_V_we1(grp_compute4_fu_624_fm_out_buff_V_we1);
    grp_compute4_fu_624->fm_out_buff_V_d1(grp_compute4_fu_624_fm_out_buff_V_d1);
    grp_compute4_fu_624->fm_out_buff_V_q1(fm_out_buff_V_q1);
    grp_store_output_fu_702 = new store_output("grp_store_output_fu_702");
    grp_store_output_fu_702->ap_clk(ap_clk);
    grp_store_output_fu_702->ap_rst(ap_rst);
    grp_store_output_fu_702->ap_start(grp_store_output_fu_702_ap_start);
    grp_store_output_fu_702->ap_done(grp_store_output_fu_702_ap_done);
    grp_store_output_fu_702->ap_idle(grp_store_output_fu_702_ap_idle);
    grp_store_output_fu_702->ap_ready(grp_store_output_fu_702_ap_ready);
    grp_store_output_fu_702->m_axi_out_V_AWVALID(grp_store_output_fu_702_m_axi_out_V_AWVALID);
    grp_store_output_fu_702->m_axi_out_V_AWREADY(m_axi_out_V_AWREADY);
    grp_store_output_fu_702->m_axi_out_V_AWADDR(grp_store_output_fu_702_m_axi_out_V_AWADDR);
    grp_store_output_fu_702->m_axi_out_V_AWID(grp_store_output_fu_702_m_axi_out_V_AWID);
    grp_store_output_fu_702->m_axi_out_V_AWLEN(grp_store_output_fu_702_m_axi_out_V_AWLEN);
    grp_store_output_fu_702->m_axi_out_V_AWSIZE(grp_store_output_fu_702_m_axi_out_V_AWSIZE);
    grp_store_output_fu_702->m_axi_out_V_AWBURST(grp_store_output_fu_702_m_axi_out_V_AWBURST);
    grp_store_output_fu_702->m_axi_out_V_AWLOCK(grp_store_output_fu_702_m_axi_out_V_AWLOCK);
    grp_store_output_fu_702->m_axi_out_V_AWCACHE(grp_store_output_fu_702_m_axi_out_V_AWCACHE);
    grp_store_output_fu_702->m_axi_out_V_AWPROT(grp_store_output_fu_702_m_axi_out_V_AWPROT);
    grp_store_output_fu_702->m_axi_out_V_AWQOS(grp_store_output_fu_702_m_axi_out_V_AWQOS);
    grp_store_output_fu_702->m_axi_out_V_AWREGION(grp_store_output_fu_702_m_axi_out_V_AWREGION);
    grp_store_output_fu_702->m_axi_out_V_AWUSER(grp_store_output_fu_702_m_axi_out_V_AWUSER);
    grp_store_output_fu_702->m_axi_out_V_WVALID(grp_store_output_fu_702_m_axi_out_V_WVALID);
    grp_store_output_fu_702->m_axi_out_V_WREADY(m_axi_out_V_WREADY);
    grp_store_output_fu_702->m_axi_out_V_WDATA(grp_store_output_fu_702_m_axi_out_V_WDATA);
    grp_store_output_fu_702->m_axi_out_V_WSTRB(grp_store_output_fu_702_m_axi_out_V_WSTRB);
    grp_store_output_fu_702->m_axi_out_V_WLAST(grp_store_output_fu_702_m_axi_out_V_WLAST);
    grp_store_output_fu_702->m_axi_out_V_WID(grp_store_output_fu_702_m_axi_out_V_WID);
    grp_store_output_fu_702->m_axi_out_V_WUSER(grp_store_output_fu_702_m_axi_out_V_WUSER);
    grp_store_output_fu_702->m_axi_out_V_ARVALID(grp_store_output_fu_702_m_axi_out_V_ARVALID);
    grp_store_output_fu_702->m_axi_out_V_ARREADY(ap_var_for_const0);
    grp_store_output_fu_702->m_axi_out_V_ARADDR(grp_store_output_fu_702_m_axi_out_V_ARADDR);
    grp_store_output_fu_702->m_axi_out_V_ARID(grp_store_output_fu_702_m_axi_out_V_ARID);
    grp_store_output_fu_702->m_axi_out_V_ARLEN(grp_store_output_fu_702_m_axi_out_V_ARLEN);
    grp_store_output_fu_702->m_axi_out_V_ARSIZE(grp_store_output_fu_702_m_axi_out_V_ARSIZE);
    grp_store_output_fu_702->m_axi_out_V_ARBURST(grp_store_output_fu_702_m_axi_out_V_ARBURST);
    grp_store_output_fu_702->m_axi_out_V_ARLOCK(grp_store_output_fu_702_m_axi_out_V_ARLOCK);
    grp_store_output_fu_702->m_axi_out_V_ARCACHE(grp_store_output_fu_702_m_axi_out_V_ARCACHE);
    grp_store_output_fu_702->m_axi_out_V_ARPROT(grp_store_output_fu_702_m_axi_out_V_ARPROT);
    grp_store_output_fu_702->m_axi_out_V_ARQOS(grp_store_output_fu_702_m_axi_out_V_ARQOS);
    grp_store_output_fu_702->m_axi_out_V_ARREGION(grp_store_output_fu_702_m_axi_out_V_ARREGION);
    grp_store_output_fu_702->m_axi_out_V_ARUSER(grp_store_output_fu_702_m_axi_out_V_ARUSER);
    grp_store_output_fu_702->m_axi_out_V_RVALID(ap_var_for_const0);
    grp_store_output_fu_702->m_axi_out_V_RREADY(grp_store_output_fu_702_m_axi_out_V_RREADY);
    grp_store_output_fu_702->m_axi_out_V_RDATA(ap_var_for_const1);
    grp_store_output_fu_702->m_axi_out_V_RLAST(ap_var_for_const0);
    grp_store_output_fu_702->m_axi_out_V_RID(ap_var_for_const2);
    grp_store_output_fu_702->m_axi_out_V_RUSER(ap_var_for_const2);
    grp_store_output_fu_702->m_axi_out_V_RRESP(ap_var_for_const3);
    grp_store_output_fu_702->m_axi_out_V_BVALID(m_axi_out_V_BVALID);
    grp_store_output_fu_702->m_axi_out_V_BREADY(grp_store_output_fu_702_m_axi_out_V_BREADY);
    grp_store_output_fu_702->m_axi_out_V_BRESP(m_axi_out_V_BRESP);
    grp_store_output_fu_702->m_axi_out_V_BID(m_axi_out_V_BID);
    grp_store_output_fu_702->m_axi_out_V_BUSER(m_axi_out_V_BUSER);
    grp_store_output_fu_702->out_V_offset(out_V_offset);
    grp_store_output_fu_702->fm_out_buff_V_address0(grp_store_output_fu_702_fm_out_buff_V_address0);
    grp_store_output_fu_702->fm_out_buff_V_ce0(grp_store_output_fu_702_fm_out_buff_V_ce0);
    grp_store_output_fu_702->fm_out_buff_V_q0(fm_out_buff_V_q0);
    grp_store_output_fu_702->m(ch_0_reg_612);
    grp_store_output_fu_702->fm_row(trunc_ln124_reg_1076);
    grp_store_output_fu_702->fm_col(trunc_ln124_1_reg_1081);
    grp_load_weight_fu_714 = new load_weight("grp_load_weight_fu_714");
    grp_load_weight_fu_714->ap_clk(ap_clk);
    grp_load_weight_fu_714->ap_rst(ap_rst);
    grp_load_weight_fu_714->ap_start(grp_load_weight_fu_714_ap_start);
    grp_load_weight_fu_714->ap_done(grp_load_weight_fu_714_ap_done);
    grp_load_weight_fu_714->ap_idle(grp_load_weight_fu_714_ap_idle);
    grp_load_weight_fu_714->ap_ready(grp_load_weight_fu_714_ap_ready);
    grp_load_weight_fu_714->m_axi_weight_V_AWVALID(grp_load_weight_fu_714_m_axi_weight_V_AWVALID);
    grp_load_weight_fu_714->m_axi_weight_V_AWREADY(ap_var_for_const0);
    grp_load_weight_fu_714->m_axi_weight_V_AWADDR(grp_load_weight_fu_714_m_axi_weight_V_AWADDR);
    grp_load_weight_fu_714->m_axi_weight_V_AWID(grp_load_weight_fu_714_m_axi_weight_V_AWID);
    grp_load_weight_fu_714->m_axi_weight_V_AWLEN(grp_load_weight_fu_714_m_axi_weight_V_AWLEN);
    grp_load_weight_fu_714->m_axi_weight_V_AWSIZE(grp_load_weight_fu_714_m_axi_weight_V_AWSIZE);
    grp_load_weight_fu_714->m_axi_weight_V_AWBURST(grp_load_weight_fu_714_m_axi_weight_V_AWBURST);
    grp_load_weight_fu_714->m_axi_weight_V_AWLOCK(grp_load_weight_fu_714_m_axi_weight_V_AWLOCK);
    grp_load_weight_fu_714->m_axi_weight_V_AWCACHE(grp_load_weight_fu_714_m_axi_weight_V_AWCACHE);
    grp_load_weight_fu_714->m_axi_weight_V_AWPROT(grp_load_weight_fu_714_m_axi_weight_V_AWPROT);
    grp_load_weight_fu_714->m_axi_weight_V_AWQOS(grp_load_weight_fu_714_m_axi_weight_V_AWQOS);
    grp_load_weight_fu_714->m_axi_weight_V_AWREGION(grp_load_weight_fu_714_m_axi_weight_V_AWREGION);
    grp_load_weight_fu_714->m_axi_weight_V_AWUSER(grp_load_weight_fu_714_m_axi_weight_V_AWUSER);
    grp_load_weight_fu_714->m_axi_weight_V_WVALID(grp_load_weight_fu_714_m_axi_weight_V_WVALID);
    grp_load_weight_fu_714->m_axi_weight_V_WREADY(ap_var_for_const0);
    grp_load_weight_fu_714->m_axi_weight_V_WDATA(grp_load_weight_fu_714_m_axi_weight_V_WDATA);
    grp_load_weight_fu_714->m_axi_weight_V_WSTRB(grp_load_weight_fu_714_m_axi_weight_V_WSTRB);
    grp_load_weight_fu_714->m_axi_weight_V_WLAST(grp_load_weight_fu_714_m_axi_weight_V_WLAST);
    grp_load_weight_fu_714->m_axi_weight_V_WID(grp_load_weight_fu_714_m_axi_weight_V_WID);
    grp_load_weight_fu_714->m_axi_weight_V_WUSER(grp_load_weight_fu_714_m_axi_weight_V_WUSER);
    grp_load_weight_fu_714->m_axi_weight_V_ARVALID(grp_load_weight_fu_714_m_axi_weight_V_ARVALID);
    grp_load_weight_fu_714->m_axi_weight_V_ARREADY(m_axi_weight_V_ARREADY);
    grp_load_weight_fu_714->m_axi_weight_V_ARADDR(grp_load_weight_fu_714_m_axi_weight_V_ARADDR);
    grp_load_weight_fu_714->m_axi_weight_V_ARID(grp_load_weight_fu_714_m_axi_weight_V_ARID);
    grp_load_weight_fu_714->m_axi_weight_V_ARLEN(grp_load_weight_fu_714_m_axi_weight_V_ARLEN);
    grp_load_weight_fu_714->m_axi_weight_V_ARSIZE(grp_load_weight_fu_714_m_axi_weight_V_ARSIZE);
    grp_load_weight_fu_714->m_axi_weight_V_ARBURST(grp_load_weight_fu_714_m_axi_weight_V_ARBURST);
    grp_load_weight_fu_714->m_axi_weight_V_ARLOCK(grp_load_weight_fu_714_m_axi_weight_V_ARLOCK);
    grp_load_weight_fu_714->m_axi_weight_V_ARCACHE(grp_load_weight_fu_714_m_axi_weight_V_ARCACHE);
    grp_load_weight_fu_714->m_axi_weight_V_ARPROT(grp_load_weight_fu_714_m_axi_weight_V_ARPROT);
    grp_load_weight_fu_714->m_axi_weight_V_ARQOS(grp_load_weight_fu_714_m_axi_weight_V_ARQOS);
    grp_load_weight_fu_714->m_axi_weight_V_ARREGION(grp_load_weight_fu_714_m_axi_weight_V_ARREGION);
    grp_load_weight_fu_714->m_axi_weight_V_ARUSER(grp_load_weight_fu_714_m_axi_weight_V_ARUSER);
    grp_load_weight_fu_714->m_axi_weight_V_RVALID(m_axi_weight_V_RVALID);
    grp_load_weight_fu_714->m_axi_weight_V_RREADY(grp_load_weight_fu_714_m_axi_weight_V_RREADY);
    grp_load_weight_fu_714->m_axi_weight_V_RDATA(m_axi_weight_V_RDATA);
    grp_load_weight_fu_714->m_axi_weight_V_RLAST(m_axi_weight_V_RLAST);
    grp_load_weight_fu_714->m_axi_weight_V_RID(m_axi_weight_V_RID);
    grp_load_weight_fu_714->m_axi_weight_V_RUSER(m_axi_weight_V_RUSER);
    grp_load_weight_fu_714->m_axi_weight_V_RRESP(m_axi_weight_V_RRESP);
    grp_load_weight_fu_714->m_axi_weight_V_BVALID(ap_var_for_const0);
    grp_load_weight_fu_714->m_axi_weight_V_BREADY(grp_load_weight_fu_714_m_axi_weight_V_BREADY);
    grp_load_weight_fu_714->m_axi_weight_V_BRESP(ap_var_for_const3);
    grp_load_weight_fu_714->m_axi_weight_V_BID(ap_var_for_const2);
    grp_load_weight_fu_714->m_axi_weight_V_BUSER(ap_var_for_const2);
    grp_load_weight_fu_714->weight_V_offset(weight_V_offset);
    grp_load_weight_fu_714->wt_buff_V_address0(grp_load_weight_fu_714_wt_buff_V_address0);
    grp_load_weight_fu_714->wt_buff_V_ce0(grp_load_weight_fu_714_wt_buff_V_ce0);
    grp_load_weight_fu_714->wt_buff_V_we0(grp_load_weight_fu_714_wt_buff_V_we0);
    grp_load_weight_fu_714->wt_buff_V_d0(grp_load_weight_fu_714_wt_buff_V_d0);
    grp_load_weight_fu_714->m(ch_0_reg_612);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );

    SC_METHOD(thread_ch_fu_740_p2);
    sensitive << ( ch_0_reg_612 );

    SC_METHOD(thread_fm_in_buff_0_V_address0);
    sensitive << ( grp_compute4_fu_624_fm_in_buff_0_V_address0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fm_in_buff_0_V_ce0);
    sensitive << ( grp_compute4_fu_624_fm_in_buff_0_V_ce0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fm_in_buff_1_V_address0);
    sensitive << ( grp_compute4_fu_624_fm_in_buff_1_V_address0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fm_in_buff_1_V_ce0);
    sensitive << ( grp_compute4_fu_624_fm_in_buff_1_V_ce0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fm_in_buff_2_V_address0);
    sensitive << ( grp_compute4_fu_624_fm_in_buff_2_V_address0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fm_in_buff_2_V_ce0);
    sensitive << ( grp_compute4_fu_624_fm_in_buff_2_V_ce0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fm_out_buff_V_address0);
    sensitive << ( grp_compute4_fu_624_fm_out_buff_V_address0 );
    sensitive << ( grp_store_output_fu_702_fm_out_buff_V_address0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fm_out_buff_V_ce0);
    sensitive << ( grp_compute4_fu_624_fm_out_buff_V_ce0 );
    sensitive << ( grp_store_output_fu_702_fm_out_buff_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fm_out_buff_V_ce1);
    sensitive << ( grp_compute4_fu_624_fm_out_buff_V_ce1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fm_out_buff_V_we0);
    sensitive << ( grp_compute4_fu_624_fm_out_buff_V_we0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fm_out_buff_V_we1);
    sensitive << ( grp_compute4_fu_624_fm_out_buff_V_we1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_compute4_fu_624_ap_start);
    sensitive << ( grp_compute4_fu_624_ap_start_reg );

    SC_METHOD(thread_grp_load_weight_fu_714_ap_start);
    sensitive << ( grp_load_weight_fu_714_ap_start_reg );

    SC_METHOD(thread_grp_store_output_fu_702_ap_start);
    sensitive << ( grp_store_output_fu_702_ap_start_reg );

    SC_METHOD(thread_m_axi_out_V_ARADDR);

    SC_METHOD(thread_m_axi_out_V_ARBURST);

    SC_METHOD(thread_m_axi_out_V_ARCACHE);

    SC_METHOD(thread_m_axi_out_V_ARID);

    SC_METHOD(thread_m_axi_out_V_ARLEN);

    SC_METHOD(thread_m_axi_out_V_ARLOCK);

    SC_METHOD(thread_m_axi_out_V_ARPROT);

    SC_METHOD(thread_m_axi_out_V_ARQOS);

    SC_METHOD(thread_m_axi_out_V_ARREGION);

    SC_METHOD(thread_m_axi_out_V_ARSIZE);

    SC_METHOD(thread_m_axi_out_V_ARUSER);

    SC_METHOD(thread_m_axi_out_V_ARVALID);

    SC_METHOD(thread_m_axi_out_V_AWADDR);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWADDR );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_AWBURST);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWBURST );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_AWCACHE);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWCACHE );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_AWID);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWID );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_AWLEN);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWLEN );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_AWLOCK);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWLOCK );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_AWPROT);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWPROT );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_AWQOS);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWQOS );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_AWREGION);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWREGION );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_AWSIZE);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWSIZE );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_AWUSER);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWUSER );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_AWVALID);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_AWVALID );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_BREADY);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_BREADY );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_RREADY);

    SC_METHOD(thread_m_axi_out_V_WDATA);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_WDATA );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_WID);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_WID );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_WLAST);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_WLAST );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_WSTRB);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_WSTRB );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_WUSER);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_WUSER );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_out_V_WVALID);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_store_output_fu_702_m_axi_out_V_WVALID );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_weight_V_ARADDR);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARADDR );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_ARBURST);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARBURST );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_ARCACHE);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARCACHE );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_ARID);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARID );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_ARLEN);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARLEN );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_ARLOCK);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARLOCK );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_ARPROT);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARPROT );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_ARQOS);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARQOS );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_ARREGION);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARREGION );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_ARSIZE);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARSIZE );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_ARUSER);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARUSER );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_ARVALID);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_ARVALID );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_AWADDR);

    SC_METHOD(thread_m_axi_weight_V_AWBURST);

    SC_METHOD(thread_m_axi_weight_V_AWCACHE);

    SC_METHOD(thread_m_axi_weight_V_AWID);

    SC_METHOD(thread_m_axi_weight_V_AWLEN);

    SC_METHOD(thread_m_axi_weight_V_AWLOCK);

    SC_METHOD(thread_m_axi_weight_V_AWPROT);

    SC_METHOD(thread_m_axi_weight_V_AWQOS);

    SC_METHOD(thread_m_axi_weight_V_AWREGION);

    SC_METHOD(thread_m_axi_weight_V_AWSIZE);

    SC_METHOD(thread_m_axi_weight_V_AWUSER);

    SC_METHOD(thread_m_axi_weight_V_AWVALID);

    SC_METHOD(thread_m_axi_weight_V_BREADY);

    SC_METHOD(thread_m_axi_weight_V_RREADY);
    sensitive << ( grp_load_weight_fu_714_m_axi_weight_V_RREADY );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_axi_weight_V_WDATA);

    SC_METHOD(thread_m_axi_weight_V_WID);

    SC_METHOD(thread_m_axi_weight_V_WLAST);

    SC_METHOD(thread_m_axi_weight_V_WSTRB);

    SC_METHOD(thread_m_axi_weight_V_WUSER);

    SC_METHOD(thread_m_axi_weight_V_WVALID);

    SC_METHOD(thread_tmp_fu_732_p3);
    sensitive << ( ch_0_reg_612 );

    SC_METHOD(thread_trunc_ln124_1_fu_728_p1);
    sensitive << ( col );

    SC_METHOD(thread_trunc_ln124_fu_724_p1);
    sensitive << ( row );

    SC_METHOD(thread_wt_buff_V_address0);
    sensitive << ( grp_compute4_fu_624_wt_buff_V_address0 );
    sensitive << ( grp_load_weight_fu_714_wt_buff_V_address0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_wt_buff_V_ce0);
    sensitive << ( grp_compute4_fu_624_wt_buff_V_ce0 );
    sensitive << ( grp_load_weight_fu_714_wt_buff_V_ce0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_wt_buff_V_ce1);
    sensitive << ( grp_compute4_fu_624_wt_buff_V_ce1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_wt_buff_V_we0);
    sensitive << ( grp_load_weight_fu_714_wt_buff_V_we0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_compute4_fu_624_ap_done );
    sensitive << ( grp_store_output_fu_702_ap_done );
    sensitive << ( grp_load_weight_fu_714_ap_done );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_732_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0000001";
    grp_compute4_fu_624_ap_start_reg = SC_LOGIC_0;
    grp_store_output_fu_702_ap_start_reg = SC_LOGIC_0;
    grp_load_weight_fu_714_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "compute_output_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, m_axi_weight_V_AWVALID, "(port)m_axi_weight_V_AWVALID");
    sc_trace(mVcdFile, m_axi_weight_V_AWREADY, "(port)m_axi_weight_V_AWREADY");
    sc_trace(mVcdFile, m_axi_weight_V_AWADDR, "(port)m_axi_weight_V_AWADDR");
    sc_trace(mVcdFile, m_axi_weight_V_AWID, "(port)m_axi_weight_V_AWID");
    sc_trace(mVcdFile, m_axi_weight_V_AWLEN, "(port)m_axi_weight_V_AWLEN");
    sc_trace(mVcdFile, m_axi_weight_V_AWSIZE, "(port)m_axi_weight_V_AWSIZE");
    sc_trace(mVcdFile, m_axi_weight_V_AWBURST, "(port)m_axi_weight_V_AWBURST");
    sc_trace(mVcdFile, m_axi_weight_V_AWLOCK, "(port)m_axi_weight_V_AWLOCK");
    sc_trace(mVcdFile, m_axi_weight_V_AWCACHE, "(port)m_axi_weight_V_AWCACHE");
    sc_trace(mVcdFile, m_axi_weight_V_AWPROT, "(port)m_axi_weight_V_AWPROT");
    sc_trace(mVcdFile, m_axi_weight_V_AWQOS, "(port)m_axi_weight_V_AWQOS");
    sc_trace(mVcdFile, m_axi_weight_V_AWREGION, "(port)m_axi_weight_V_AWREGION");
    sc_trace(mVcdFile, m_axi_weight_V_AWUSER, "(port)m_axi_weight_V_AWUSER");
    sc_trace(mVcdFile, m_axi_weight_V_WVALID, "(port)m_axi_weight_V_WVALID");
    sc_trace(mVcdFile, m_axi_weight_V_WREADY, "(port)m_axi_weight_V_WREADY");
    sc_trace(mVcdFile, m_axi_weight_V_WDATA, "(port)m_axi_weight_V_WDATA");
    sc_trace(mVcdFile, m_axi_weight_V_WSTRB, "(port)m_axi_weight_V_WSTRB");
    sc_trace(mVcdFile, m_axi_weight_V_WLAST, "(port)m_axi_weight_V_WLAST");
    sc_trace(mVcdFile, m_axi_weight_V_WID, "(port)m_axi_weight_V_WID");
    sc_trace(mVcdFile, m_axi_weight_V_WUSER, "(port)m_axi_weight_V_WUSER");
    sc_trace(mVcdFile, m_axi_weight_V_ARVALID, "(port)m_axi_weight_V_ARVALID");
    sc_trace(mVcdFile, m_axi_weight_V_ARREADY, "(port)m_axi_weight_V_ARREADY");
    sc_trace(mVcdFile, m_axi_weight_V_ARADDR, "(port)m_axi_weight_V_ARADDR");
    sc_trace(mVcdFile, m_axi_weight_V_ARID, "(port)m_axi_weight_V_ARID");
    sc_trace(mVcdFile, m_axi_weight_V_ARLEN, "(port)m_axi_weight_V_ARLEN");
    sc_trace(mVcdFile, m_axi_weight_V_ARSIZE, "(port)m_axi_weight_V_ARSIZE");
    sc_trace(mVcdFile, m_axi_weight_V_ARBURST, "(port)m_axi_weight_V_ARBURST");
    sc_trace(mVcdFile, m_axi_weight_V_ARLOCK, "(port)m_axi_weight_V_ARLOCK");
    sc_trace(mVcdFile, m_axi_weight_V_ARCACHE, "(port)m_axi_weight_V_ARCACHE");
    sc_trace(mVcdFile, m_axi_weight_V_ARPROT, "(port)m_axi_weight_V_ARPROT");
    sc_trace(mVcdFile, m_axi_weight_V_ARQOS, "(port)m_axi_weight_V_ARQOS");
    sc_trace(mVcdFile, m_axi_weight_V_ARREGION, "(port)m_axi_weight_V_ARREGION");
    sc_trace(mVcdFile, m_axi_weight_V_ARUSER, "(port)m_axi_weight_V_ARUSER");
    sc_trace(mVcdFile, m_axi_weight_V_RVALID, "(port)m_axi_weight_V_RVALID");
    sc_trace(mVcdFile, m_axi_weight_V_RREADY, "(port)m_axi_weight_V_RREADY");
    sc_trace(mVcdFile, m_axi_weight_V_RDATA, "(port)m_axi_weight_V_RDATA");
    sc_trace(mVcdFile, m_axi_weight_V_RLAST, "(port)m_axi_weight_V_RLAST");
    sc_trace(mVcdFile, m_axi_weight_V_RID, "(port)m_axi_weight_V_RID");
    sc_trace(mVcdFile, m_axi_weight_V_RUSER, "(port)m_axi_weight_V_RUSER");
    sc_trace(mVcdFile, m_axi_weight_V_RRESP, "(port)m_axi_weight_V_RRESP");
    sc_trace(mVcdFile, m_axi_weight_V_BVALID, "(port)m_axi_weight_V_BVALID");
    sc_trace(mVcdFile, m_axi_weight_V_BREADY, "(port)m_axi_weight_V_BREADY");
    sc_trace(mVcdFile, m_axi_weight_V_BRESP, "(port)m_axi_weight_V_BRESP");
    sc_trace(mVcdFile, m_axi_weight_V_BID, "(port)m_axi_weight_V_BID");
    sc_trace(mVcdFile, m_axi_weight_V_BUSER, "(port)m_axi_weight_V_BUSER");
    sc_trace(mVcdFile, weight_V_offset, "(port)weight_V_offset");
    sc_trace(mVcdFile, m_axi_out_V_AWVALID, "(port)m_axi_out_V_AWVALID");
    sc_trace(mVcdFile, m_axi_out_V_AWREADY, "(port)m_axi_out_V_AWREADY");
    sc_trace(mVcdFile, m_axi_out_V_AWADDR, "(port)m_axi_out_V_AWADDR");
    sc_trace(mVcdFile, m_axi_out_V_AWID, "(port)m_axi_out_V_AWID");
    sc_trace(mVcdFile, m_axi_out_V_AWLEN, "(port)m_axi_out_V_AWLEN");
    sc_trace(mVcdFile, m_axi_out_V_AWSIZE, "(port)m_axi_out_V_AWSIZE");
    sc_trace(mVcdFile, m_axi_out_V_AWBURST, "(port)m_axi_out_V_AWBURST");
    sc_trace(mVcdFile, m_axi_out_V_AWLOCK, "(port)m_axi_out_V_AWLOCK");
    sc_trace(mVcdFile, m_axi_out_V_AWCACHE, "(port)m_axi_out_V_AWCACHE");
    sc_trace(mVcdFile, m_axi_out_V_AWPROT, "(port)m_axi_out_V_AWPROT");
    sc_trace(mVcdFile, m_axi_out_V_AWQOS, "(port)m_axi_out_V_AWQOS");
    sc_trace(mVcdFile, m_axi_out_V_AWREGION, "(port)m_axi_out_V_AWREGION");
    sc_trace(mVcdFile, m_axi_out_V_AWUSER, "(port)m_axi_out_V_AWUSER");
    sc_trace(mVcdFile, m_axi_out_V_WVALID, "(port)m_axi_out_V_WVALID");
    sc_trace(mVcdFile, m_axi_out_V_WREADY, "(port)m_axi_out_V_WREADY");
    sc_trace(mVcdFile, m_axi_out_V_WDATA, "(port)m_axi_out_V_WDATA");
    sc_trace(mVcdFile, m_axi_out_V_WSTRB, "(port)m_axi_out_V_WSTRB");
    sc_trace(mVcdFile, m_axi_out_V_WLAST, "(port)m_axi_out_V_WLAST");
    sc_trace(mVcdFile, m_axi_out_V_WID, "(port)m_axi_out_V_WID");
    sc_trace(mVcdFile, m_axi_out_V_WUSER, "(port)m_axi_out_V_WUSER");
    sc_trace(mVcdFile, m_axi_out_V_ARVALID, "(port)m_axi_out_V_ARVALID");
    sc_trace(mVcdFile, m_axi_out_V_ARREADY, "(port)m_axi_out_V_ARREADY");
    sc_trace(mVcdFile, m_axi_out_V_ARADDR, "(port)m_axi_out_V_ARADDR");
    sc_trace(mVcdFile, m_axi_out_V_ARID, "(port)m_axi_out_V_ARID");
    sc_trace(mVcdFile, m_axi_out_V_ARLEN, "(port)m_axi_out_V_ARLEN");
    sc_trace(mVcdFile, m_axi_out_V_ARSIZE, "(port)m_axi_out_V_ARSIZE");
    sc_trace(mVcdFile, m_axi_out_V_ARBURST, "(port)m_axi_out_V_ARBURST");
    sc_trace(mVcdFile, m_axi_out_V_ARLOCK, "(port)m_axi_out_V_ARLOCK");
    sc_trace(mVcdFile, m_axi_out_V_ARCACHE, "(port)m_axi_out_V_ARCACHE");
    sc_trace(mVcdFile, m_axi_out_V_ARPROT, "(port)m_axi_out_V_ARPROT");
    sc_trace(mVcdFile, m_axi_out_V_ARQOS, "(port)m_axi_out_V_ARQOS");
    sc_trace(mVcdFile, m_axi_out_V_ARREGION, "(port)m_axi_out_V_ARREGION");
    sc_trace(mVcdFile, m_axi_out_V_ARUSER, "(port)m_axi_out_V_ARUSER");
    sc_trace(mVcdFile, m_axi_out_V_RVALID, "(port)m_axi_out_V_RVALID");
    sc_trace(mVcdFile, m_axi_out_V_RREADY, "(port)m_axi_out_V_RREADY");
    sc_trace(mVcdFile, m_axi_out_V_RDATA, "(port)m_axi_out_V_RDATA");
    sc_trace(mVcdFile, m_axi_out_V_RLAST, "(port)m_axi_out_V_RLAST");
    sc_trace(mVcdFile, m_axi_out_V_RID, "(port)m_axi_out_V_RID");
    sc_trace(mVcdFile, m_axi_out_V_RUSER, "(port)m_axi_out_V_RUSER");
    sc_trace(mVcdFile, m_axi_out_V_RRESP, "(port)m_axi_out_V_RRESP");
    sc_trace(mVcdFile, m_axi_out_V_BVALID, "(port)m_axi_out_V_BVALID");
    sc_trace(mVcdFile, m_axi_out_V_BREADY, "(port)m_axi_out_V_BREADY");
    sc_trace(mVcdFile, m_axi_out_V_BRESP, "(port)m_axi_out_V_BRESP");
    sc_trace(mVcdFile, m_axi_out_V_BID, "(port)m_axi_out_V_BID");
    sc_trace(mVcdFile, m_axi_out_V_BUSER, "(port)m_axi_out_V_BUSER");
    sc_trace(mVcdFile, out_V_offset, "(port)out_V_offset");
    sc_trace(mVcdFile, fm_in_buff_0_V_address0, "(port)fm_in_buff_0_V_address0");
    sc_trace(mVcdFile, fm_in_buff_0_V_ce0, "(port)fm_in_buff_0_V_ce0");
    sc_trace(mVcdFile, fm_in_buff_0_V_q0, "(port)fm_in_buff_0_V_q0");
    sc_trace(mVcdFile, fm_in_buff_1_V_address0, "(port)fm_in_buff_1_V_address0");
    sc_trace(mVcdFile, fm_in_buff_1_V_ce0, "(port)fm_in_buff_1_V_ce0");
    sc_trace(mVcdFile, fm_in_buff_1_V_q0, "(port)fm_in_buff_1_V_q0");
    sc_trace(mVcdFile, fm_in_buff_2_V_address0, "(port)fm_in_buff_2_V_address0");
    sc_trace(mVcdFile, fm_in_buff_2_V_ce0, "(port)fm_in_buff_2_V_ce0");
    sc_trace(mVcdFile, fm_in_buff_2_V_q0, "(port)fm_in_buff_2_V_q0");
    sc_trace(mVcdFile, bias_buff_0_V_read, "(port)bias_buff_0_V_read");
    sc_trace(mVcdFile, bias_buff_1_V_read, "(port)bias_buff_1_V_read");
    sc_trace(mVcdFile, bias_buff_2_V_read, "(port)bias_buff_2_V_read");
    sc_trace(mVcdFile, bias_buff_3_V_read, "(port)bias_buff_3_V_read");
    sc_trace(mVcdFile, bias_buff_4_V_read, "(port)bias_buff_4_V_read");
    sc_trace(mVcdFile, bias_buff_5_V_read, "(port)bias_buff_5_V_read");
    sc_trace(mVcdFile, bias_buff_6_V_read, "(port)bias_buff_6_V_read");
    sc_trace(mVcdFile, bias_buff_7_V_read, "(port)bias_buff_7_V_read");
    sc_trace(mVcdFile, bias_buff_8_V_read, "(port)bias_buff_8_V_read");
    sc_trace(mVcdFile, bias_buff_9_V_read, "(port)bias_buff_9_V_read");
    sc_trace(mVcdFile, bias_buff_10_V_read, "(port)bias_buff_10_V_read");
    sc_trace(mVcdFile, bias_buff_11_V_read, "(port)bias_buff_11_V_read");
    sc_trace(mVcdFile, bias_buff_12_V_read, "(port)bias_buff_12_V_read");
    sc_trace(mVcdFile, bias_buff_13_V_read, "(port)bias_buff_13_V_read");
    sc_trace(mVcdFile, bias_buff_14_V_read, "(port)bias_buff_14_V_read");
    sc_trace(mVcdFile, bias_buff_15_V_read, "(port)bias_buff_15_V_read");
    sc_trace(mVcdFile, bias_buff_16_V_read, "(port)bias_buff_16_V_read");
    sc_trace(mVcdFile, bias_buff_17_V_read, "(port)bias_buff_17_V_read");
    sc_trace(mVcdFile, bias_buff_18_V_read, "(port)bias_buff_18_V_read");
    sc_trace(mVcdFile, bias_buff_19_V_read, "(port)bias_buff_19_V_read");
    sc_trace(mVcdFile, bias_buff_20_V_read, "(port)bias_buff_20_V_read");
    sc_trace(mVcdFile, bias_buff_21_V_read, "(port)bias_buff_21_V_read");
    sc_trace(mVcdFile, bias_buff_22_V_read, "(port)bias_buff_22_V_read");
    sc_trace(mVcdFile, bias_buff_23_V_read, "(port)bias_buff_23_V_read");
    sc_trace(mVcdFile, bias_buff_24_V_read, "(port)bias_buff_24_V_read");
    sc_trace(mVcdFile, bias_buff_25_V_read, "(port)bias_buff_25_V_read");
    sc_trace(mVcdFile, bias_buff_26_V_read, "(port)bias_buff_26_V_read");
    sc_trace(mVcdFile, bias_buff_27_V_read, "(port)bias_buff_27_V_read");
    sc_trace(mVcdFile, bias_buff_28_V_read, "(port)bias_buff_28_V_read");
    sc_trace(mVcdFile, bias_buff_29_V_read, "(port)bias_buff_29_V_read");
    sc_trace(mVcdFile, bias_buff_30_V_read, "(port)bias_buff_30_V_read");
    sc_trace(mVcdFile, bias_buff_31_V_read, "(port)bias_buff_31_V_read");
    sc_trace(mVcdFile, bias_buff_32_V_read, "(port)bias_buff_32_V_read");
    sc_trace(mVcdFile, bias_buff_33_V_read, "(port)bias_buff_33_V_read");
    sc_trace(mVcdFile, bias_buff_34_V_read, "(port)bias_buff_34_V_read");
    sc_trace(mVcdFile, bias_buff_35_V_read, "(port)bias_buff_35_V_read");
    sc_trace(mVcdFile, bias_buff_36_V_read, "(port)bias_buff_36_V_read");
    sc_trace(mVcdFile, bias_buff_37_V_read, "(port)bias_buff_37_V_read");
    sc_trace(mVcdFile, bias_buff_38_V_read, "(port)bias_buff_38_V_read");
    sc_trace(mVcdFile, bias_buff_39_V_read, "(port)bias_buff_39_V_read");
    sc_trace(mVcdFile, bias_buff_40_V_read, "(port)bias_buff_40_V_read");
    sc_trace(mVcdFile, bias_buff_41_V_read, "(port)bias_buff_41_V_read");
    sc_trace(mVcdFile, bias_buff_42_V_read, "(port)bias_buff_42_V_read");
    sc_trace(mVcdFile, bias_buff_43_V_read, "(port)bias_buff_43_V_read");
    sc_trace(mVcdFile, bias_buff_44_V_read, "(port)bias_buff_44_V_read");
    sc_trace(mVcdFile, bias_buff_45_V_read, "(port)bias_buff_45_V_read");
    sc_trace(mVcdFile, bias_buff_46_V_read, "(port)bias_buff_46_V_read");
    sc_trace(mVcdFile, bias_buff_47_V_read, "(port)bias_buff_47_V_read");
    sc_trace(mVcdFile, bias_buff_48_V_read, "(port)bias_buff_48_V_read");
    sc_trace(mVcdFile, bias_buff_49_V_read, "(port)bias_buff_49_V_read");
    sc_trace(mVcdFile, bias_buff_50_V_read, "(port)bias_buff_50_V_read");
    sc_trace(mVcdFile, bias_buff_51_V_read, "(port)bias_buff_51_V_read");
    sc_trace(mVcdFile, bias_buff_52_V_read, "(port)bias_buff_52_V_read");
    sc_trace(mVcdFile, bias_buff_53_V_read, "(port)bias_buff_53_V_read");
    sc_trace(mVcdFile, bias_buff_54_V_read, "(port)bias_buff_54_V_read");
    sc_trace(mVcdFile, bias_buff_55_V_read, "(port)bias_buff_55_V_read");
    sc_trace(mVcdFile, bias_buff_56_V_read, "(port)bias_buff_56_V_read");
    sc_trace(mVcdFile, bias_buff_57_V_read, "(port)bias_buff_57_V_read");
    sc_trace(mVcdFile, bias_buff_58_V_read, "(port)bias_buff_58_V_read");
    sc_trace(mVcdFile, bias_buff_59_V_read, "(port)bias_buff_59_V_read");
    sc_trace(mVcdFile, bias_buff_60_V_read, "(port)bias_buff_60_V_read");
    sc_trace(mVcdFile, bias_buff_61_V_read, "(port)bias_buff_61_V_read");
    sc_trace(mVcdFile, bias_buff_62_V_read, "(port)bias_buff_62_V_read");
    sc_trace(mVcdFile, bias_buff_63_V_read, "(port)bias_buff_63_V_read");
    sc_trace(mVcdFile, row, "(port)row");
    sc_trace(mVcdFile, col, "(port)col");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, trunc_ln124_fu_724_p1, "trunc_ln124_fu_724_p1");
    sc_trace(mVcdFile, trunc_ln124_reg_1076, "trunc_ln124_reg_1076");
    sc_trace(mVcdFile, trunc_ln124_1_fu_728_p1, "trunc_ln124_1_fu_728_p1");
    sc_trace(mVcdFile, trunc_ln124_1_reg_1081, "trunc_ln124_1_reg_1081");
    sc_trace(mVcdFile, ch_fu_740_p2, "ch_fu_740_p2");
    sc_trace(mVcdFile, ch_reg_1089, "ch_reg_1089");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, wt_buff_V_address0, "wt_buff_V_address0");
    sc_trace(mVcdFile, wt_buff_V_ce0, "wt_buff_V_ce0");
    sc_trace(mVcdFile, wt_buff_V_we0, "wt_buff_V_we0");
    sc_trace(mVcdFile, wt_buff_V_q0, "wt_buff_V_q0");
    sc_trace(mVcdFile, wt_buff_V_ce1, "wt_buff_V_ce1");
    sc_trace(mVcdFile, wt_buff_V_q1, "wt_buff_V_q1");
    sc_trace(mVcdFile, fm_out_buff_V_address0, "fm_out_buff_V_address0");
    sc_trace(mVcdFile, fm_out_buff_V_ce0, "fm_out_buff_V_ce0");
    sc_trace(mVcdFile, fm_out_buff_V_we0, "fm_out_buff_V_we0");
    sc_trace(mVcdFile, fm_out_buff_V_q0, "fm_out_buff_V_q0");
    sc_trace(mVcdFile, fm_out_buff_V_ce1, "fm_out_buff_V_ce1");
    sc_trace(mVcdFile, fm_out_buff_V_we1, "fm_out_buff_V_we1");
    sc_trace(mVcdFile, fm_out_buff_V_q1, "fm_out_buff_V_q1");
    sc_trace(mVcdFile, grp_compute4_fu_624_ap_start, "grp_compute4_fu_624_ap_start");
    sc_trace(mVcdFile, grp_compute4_fu_624_ap_done, "grp_compute4_fu_624_ap_done");
    sc_trace(mVcdFile, grp_compute4_fu_624_ap_idle, "grp_compute4_fu_624_ap_idle");
    sc_trace(mVcdFile, grp_compute4_fu_624_ap_ready, "grp_compute4_fu_624_ap_ready");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_in_buff_0_V_address0, "grp_compute4_fu_624_fm_in_buff_0_V_address0");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_in_buff_0_V_ce0, "grp_compute4_fu_624_fm_in_buff_0_V_ce0");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_in_buff_1_V_address0, "grp_compute4_fu_624_fm_in_buff_1_V_address0");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_in_buff_1_V_ce0, "grp_compute4_fu_624_fm_in_buff_1_V_ce0");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_in_buff_2_V_address0, "grp_compute4_fu_624_fm_in_buff_2_V_address0");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_in_buff_2_V_ce0, "grp_compute4_fu_624_fm_in_buff_2_V_ce0");
    sc_trace(mVcdFile, grp_compute4_fu_624_wt_buff_V_address0, "grp_compute4_fu_624_wt_buff_V_address0");
    sc_trace(mVcdFile, grp_compute4_fu_624_wt_buff_V_ce0, "grp_compute4_fu_624_wt_buff_V_ce0");
    sc_trace(mVcdFile, grp_compute4_fu_624_wt_buff_V_address1, "grp_compute4_fu_624_wt_buff_V_address1");
    sc_trace(mVcdFile, grp_compute4_fu_624_wt_buff_V_ce1, "grp_compute4_fu_624_wt_buff_V_ce1");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_out_buff_V_address0, "grp_compute4_fu_624_fm_out_buff_V_address0");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_out_buff_V_ce0, "grp_compute4_fu_624_fm_out_buff_V_ce0");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_out_buff_V_we0, "grp_compute4_fu_624_fm_out_buff_V_we0");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_out_buff_V_d0, "grp_compute4_fu_624_fm_out_buff_V_d0");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_out_buff_V_address1, "grp_compute4_fu_624_fm_out_buff_V_address1");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_out_buff_V_ce1, "grp_compute4_fu_624_fm_out_buff_V_ce1");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_out_buff_V_we1, "grp_compute4_fu_624_fm_out_buff_V_we1");
    sc_trace(mVcdFile, grp_compute4_fu_624_fm_out_buff_V_d1, "grp_compute4_fu_624_fm_out_buff_V_d1");
    sc_trace(mVcdFile, grp_store_output_fu_702_ap_start, "grp_store_output_fu_702_ap_start");
    sc_trace(mVcdFile, grp_store_output_fu_702_ap_done, "grp_store_output_fu_702_ap_done");
    sc_trace(mVcdFile, grp_store_output_fu_702_ap_idle, "grp_store_output_fu_702_ap_idle");
    sc_trace(mVcdFile, grp_store_output_fu_702_ap_ready, "grp_store_output_fu_702_ap_ready");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWVALID, "grp_store_output_fu_702_m_axi_out_V_AWVALID");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWADDR, "grp_store_output_fu_702_m_axi_out_V_AWADDR");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWID, "grp_store_output_fu_702_m_axi_out_V_AWID");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWLEN, "grp_store_output_fu_702_m_axi_out_V_AWLEN");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWSIZE, "grp_store_output_fu_702_m_axi_out_V_AWSIZE");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWBURST, "grp_store_output_fu_702_m_axi_out_V_AWBURST");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWLOCK, "grp_store_output_fu_702_m_axi_out_V_AWLOCK");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWCACHE, "grp_store_output_fu_702_m_axi_out_V_AWCACHE");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWPROT, "grp_store_output_fu_702_m_axi_out_V_AWPROT");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWQOS, "grp_store_output_fu_702_m_axi_out_V_AWQOS");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWREGION, "grp_store_output_fu_702_m_axi_out_V_AWREGION");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_AWUSER, "grp_store_output_fu_702_m_axi_out_V_AWUSER");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_WVALID, "grp_store_output_fu_702_m_axi_out_V_WVALID");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_WDATA, "grp_store_output_fu_702_m_axi_out_V_WDATA");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_WSTRB, "grp_store_output_fu_702_m_axi_out_V_WSTRB");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_WLAST, "grp_store_output_fu_702_m_axi_out_V_WLAST");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_WID, "grp_store_output_fu_702_m_axi_out_V_WID");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_WUSER, "grp_store_output_fu_702_m_axi_out_V_WUSER");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARVALID, "grp_store_output_fu_702_m_axi_out_V_ARVALID");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARADDR, "grp_store_output_fu_702_m_axi_out_V_ARADDR");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARID, "grp_store_output_fu_702_m_axi_out_V_ARID");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARLEN, "grp_store_output_fu_702_m_axi_out_V_ARLEN");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARSIZE, "grp_store_output_fu_702_m_axi_out_V_ARSIZE");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARBURST, "grp_store_output_fu_702_m_axi_out_V_ARBURST");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARLOCK, "grp_store_output_fu_702_m_axi_out_V_ARLOCK");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARCACHE, "grp_store_output_fu_702_m_axi_out_V_ARCACHE");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARPROT, "grp_store_output_fu_702_m_axi_out_V_ARPROT");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARQOS, "grp_store_output_fu_702_m_axi_out_V_ARQOS");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARREGION, "grp_store_output_fu_702_m_axi_out_V_ARREGION");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_ARUSER, "grp_store_output_fu_702_m_axi_out_V_ARUSER");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_RREADY, "grp_store_output_fu_702_m_axi_out_V_RREADY");
    sc_trace(mVcdFile, grp_store_output_fu_702_m_axi_out_V_BREADY, "grp_store_output_fu_702_m_axi_out_V_BREADY");
    sc_trace(mVcdFile, grp_store_output_fu_702_fm_out_buff_V_address0, "grp_store_output_fu_702_fm_out_buff_V_address0");
    sc_trace(mVcdFile, grp_store_output_fu_702_fm_out_buff_V_ce0, "grp_store_output_fu_702_fm_out_buff_V_ce0");
    sc_trace(mVcdFile, grp_load_weight_fu_714_ap_start, "grp_load_weight_fu_714_ap_start");
    sc_trace(mVcdFile, grp_load_weight_fu_714_ap_done, "grp_load_weight_fu_714_ap_done");
    sc_trace(mVcdFile, grp_load_weight_fu_714_ap_idle, "grp_load_weight_fu_714_ap_idle");
    sc_trace(mVcdFile, grp_load_weight_fu_714_ap_ready, "grp_load_weight_fu_714_ap_ready");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWVALID, "grp_load_weight_fu_714_m_axi_weight_V_AWVALID");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWADDR, "grp_load_weight_fu_714_m_axi_weight_V_AWADDR");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWID, "grp_load_weight_fu_714_m_axi_weight_V_AWID");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWLEN, "grp_load_weight_fu_714_m_axi_weight_V_AWLEN");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWSIZE, "grp_load_weight_fu_714_m_axi_weight_V_AWSIZE");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWBURST, "grp_load_weight_fu_714_m_axi_weight_V_AWBURST");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWLOCK, "grp_load_weight_fu_714_m_axi_weight_V_AWLOCK");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWCACHE, "grp_load_weight_fu_714_m_axi_weight_V_AWCACHE");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWPROT, "grp_load_weight_fu_714_m_axi_weight_V_AWPROT");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWQOS, "grp_load_weight_fu_714_m_axi_weight_V_AWQOS");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWREGION, "grp_load_weight_fu_714_m_axi_weight_V_AWREGION");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_AWUSER, "grp_load_weight_fu_714_m_axi_weight_V_AWUSER");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_WVALID, "grp_load_weight_fu_714_m_axi_weight_V_WVALID");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_WDATA, "grp_load_weight_fu_714_m_axi_weight_V_WDATA");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_WSTRB, "grp_load_weight_fu_714_m_axi_weight_V_WSTRB");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_WLAST, "grp_load_weight_fu_714_m_axi_weight_V_WLAST");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_WID, "grp_load_weight_fu_714_m_axi_weight_V_WID");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_WUSER, "grp_load_weight_fu_714_m_axi_weight_V_WUSER");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARVALID, "grp_load_weight_fu_714_m_axi_weight_V_ARVALID");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARADDR, "grp_load_weight_fu_714_m_axi_weight_V_ARADDR");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARID, "grp_load_weight_fu_714_m_axi_weight_V_ARID");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARLEN, "grp_load_weight_fu_714_m_axi_weight_V_ARLEN");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARSIZE, "grp_load_weight_fu_714_m_axi_weight_V_ARSIZE");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARBURST, "grp_load_weight_fu_714_m_axi_weight_V_ARBURST");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARLOCK, "grp_load_weight_fu_714_m_axi_weight_V_ARLOCK");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARCACHE, "grp_load_weight_fu_714_m_axi_weight_V_ARCACHE");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARPROT, "grp_load_weight_fu_714_m_axi_weight_V_ARPROT");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARQOS, "grp_load_weight_fu_714_m_axi_weight_V_ARQOS");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARREGION, "grp_load_weight_fu_714_m_axi_weight_V_ARREGION");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_ARUSER, "grp_load_weight_fu_714_m_axi_weight_V_ARUSER");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_RREADY, "grp_load_weight_fu_714_m_axi_weight_V_RREADY");
    sc_trace(mVcdFile, grp_load_weight_fu_714_m_axi_weight_V_BREADY, "grp_load_weight_fu_714_m_axi_weight_V_BREADY");
    sc_trace(mVcdFile, grp_load_weight_fu_714_wt_buff_V_address0, "grp_load_weight_fu_714_wt_buff_V_address0");
    sc_trace(mVcdFile, grp_load_weight_fu_714_wt_buff_V_ce0, "grp_load_weight_fu_714_wt_buff_V_ce0");
    sc_trace(mVcdFile, grp_load_weight_fu_714_wt_buff_V_we0, "grp_load_weight_fu_714_wt_buff_V_we0");
    sc_trace(mVcdFile, grp_load_weight_fu_714_wt_buff_V_d0, "grp_load_weight_fu_714_wt_buff_V_d0");
    sc_trace(mVcdFile, ch_0_reg_612, "ch_0_reg_612");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_compute4_fu_624_ap_start_reg, "grp_compute4_fu_624_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_store_output_fu_702_ap_start_reg, "grp_store_output_fu_702_ap_start_reg");
    sc_trace(mVcdFile, grp_load_weight_fu_714_ap_start_reg, "grp_load_weight_fu_714_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_732_p3, "tmp_fu_732_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

compute_output::~compute_output() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete wt_buff_V_U;
    delete fm_out_buff_V_U;
    delete grp_compute4_fu_624;
    delete grp_store_output_fu_702;
    delete grp_load_weight_fu_714;
}

void compute_output::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_0;
}

void compute_output::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv1_0;
}

void compute_output::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv2_0;
}

void compute_output::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_0;
}

void compute_output::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ch_0_reg_612 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(grp_store_output_fu_702_ap_done.read(), ap_const_logic_1))) {
        ch_0_reg_612 = ch_reg_1089.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_compute4_fu_624_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            grp_compute4_fu_624_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_compute4_fu_624_ap_ready.read())) {
            grp_compute4_fu_624_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_load_weight_fu_714_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_732_p3.read()))) {
            grp_load_weight_fu_714_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_load_weight_fu_714_ap_ready.read())) {
            grp_load_weight_fu_714_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_store_output_fu_702_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_store_output_fu_702_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_store_output_fu_702_ap_ready.read())) {
            grp_store_output_fu_702_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ch_reg_1089 = ch_fu_740_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        trunc_ln124_1_reg_1081 = trunc_ln124_1_fu_728_p1.read();
        trunc_ln124_reg_1076 = trunc_ln124_fu_724_p1.read();
    }
}

void compute_output::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void compute_output::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void compute_output::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void compute_output::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void compute_output::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void compute_output::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void compute_output::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void compute_output::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_fu_732_p3.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void compute_output::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void compute_output::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_732_p3.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void compute_output::thread_ch_fu_740_p2() {
    ch_fu_740_p2 = (!ch_0_reg_612.read().is_01() || !ap_const_lv7_10.is_01())? sc_lv<7>(): (sc_biguint<7>(ch_0_reg_612.read()) + sc_biguint<7>(ap_const_lv7_10));
}

void compute_output::thread_fm_in_buff_0_V_address0() {
    fm_in_buff_0_V_address0 = grp_compute4_fu_624_fm_in_buff_0_V_address0.read();
}

void compute_output::thread_fm_in_buff_0_V_ce0() {
    fm_in_buff_0_V_ce0 = grp_compute4_fu_624_fm_in_buff_0_V_ce0.read();
}

void compute_output::thread_fm_in_buff_1_V_address0() {
    fm_in_buff_1_V_address0 = grp_compute4_fu_624_fm_in_buff_1_V_address0.read();
}

void compute_output::thread_fm_in_buff_1_V_ce0() {
    fm_in_buff_1_V_ce0 = grp_compute4_fu_624_fm_in_buff_1_V_ce0.read();
}

void compute_output::thread_fm_in_buff_2_V_address0() {
    fm_in_buff_2_V_address0 = grp_compute4_fu_624_fm_in_buff_2_V_address0.read();
}

void compute_output::thread_fm_in_buff_2_V_ce0() {
    fm_in_buff_2_V_ce0 = grp_compute4_fu_624_fm_in_buff_2_V_ce0.read();
}

void compute_output::thread_fm_out_buff_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        fm_out_buff_V_address0 = grp_store_output_fu_702_fm_out_buff_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        fm_out_buff_V_address0 = grp_compute4_fu_624_fm_out_buff_V_address0.read();
    } else {
        fm_out_buff_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void compute_output::thread_fm_out_buff_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        fm_out_buff_V_ce0 = grp_store_output_fu_702_fm_out_buff_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        fm_out_buff_V_ce0 = grp_compute4_fu_624_fm_out_buff_V_ce0.read();
    } else {
        fm_out_buff_V_ce0 = ap_const_logic_0;
    }
}

void compute_output::thread_fm_out_buff_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        fm_out_buff_V_ce1 = grp_compute4_fu_624_fm_out_buff_V_ce1.read();
    } else {
        fm_out_buff_V_ce1 = ap_const_logic_0;
    }
}

void compute_output::thread_fm_out_buff_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        fm_out_buff_V_we0 = grp_compute4_fu_624_fm_out_buff_V_we0.read();
    } else {
        fm_out_buff_V_we0 = ap_const_logic_0;
    }
}

void compute_output::thread_fm_out_buff_V_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        fm_out_buff_V_we1 = grp_compute4_fu_624_fm_out_buff_V_we1.read();
    } else {
        fm_out_buff_V_we1 = ap_const_logic_0;
    }
}

void compute_output::thread_grp_compute4_fu_624_ap_start() {
    grp_compute4_fu_624_ap_start = grp_compute4_fu_624_ap_start_reg.read();
}

void compute_output::thread_grp_load_weight_fu_714_ap_start() {
    grp_load_weight_fu_714_ap_start = grp_load_weight_fu_714_ap_start_reg.read();
}

void compute_output::thread_grp_store_output_fu_702_ap_start() {
    grp_store_output_fu_702_ap_start = grp_store_output_fu_702_ap_start_reg.read();
}

void compute_output::thread_m_axi_out_V_ARADDR() {
    m_axi_out_V_ARADDR = ap_const_lv32_0;
}

void compute_output::thread_m_axi_out_V_ARBURST() {
    m_axi_out_V_ARBURST = ap_const_lv2_0;
}

void compute_output::thread_m_axi_out_V_ARCACHE() {
    m_axi_out_V_ARCACHE = ap_const_lv4_0;
}

void compute_output::thread_m_axi_out_V_ARID() {
    m_axi_out_V_ARID = ap_const_lv1_0;
}

void compute_output::thread_m_axi_out_V_ARLEN() {
    m_axi_out_V_ARLEN = ap_const_lv32_0;
}

void compute_output::thread_m_axi_out_V_ARLOCK() {
    m_axi_out_V_ARLOCK = ap_const_lv2_0;
}

void compute_output::thread_m_axi_out_V_ARPROT() {
    m_axi_out_V_ARPROT = ap_const_lv3_0;
}

void compute_output::thread_m_axi_out_V_ARQOS() {
    m_axi_out_V_ARQOS = ap_const_lv4_0;
}

void compute_output::thread_m_axi_out_V_ARREGION() {
    m_axi_out_V_ARREGION = ap_const_lv4_0;
}

void compute_output::thread_m_axi_out_V_ARSIZE() {
    m_axi_out_V_ARSIZE = ap_const_lv3_0;
}

void compute_output::thread_m_axi_out_V_ARUSER() {
    m_axi_out_V_ARUSER = ap_const_lv1_0;
}

void compute_output::thread_m_axi_out_V_ARVALID() {
    m_axi_out_V_ARVALID = ap_const_logic_0;
}

void compute_output::thread_m_axi_out_V_AWADDR() {
    m_axi_out_V_AWADDR = grp_store_output_fu_702_m_axi_out_V_AWADDR.read();
}

void compute_output::thread_m_axi_out_V_AWBURST() {
    m_axi_out_V_AWBURST = grp_store_output_fu_702_m_axi_out_V_AWBURST.read();
}

void compute_output::thread_m_axi_out_V_AWCACHE() {
    m_axi_out_V_AWCACHE = grp_store_output_fu_702_m_axi_out_V_AWCACHE.read();
}

void compute_output::thread_m_axi_out_V_AWID() {
    m_axi_out_V_AWID = grp_store_output_fu_702_m_axi_out_V_AWID.read();
}

void compute_output::thread_m_axi_out_V_AWLEN() {
    m_axi_out_V_AWLEN = grp_store_output_fu_702_m_axi_out_V_AWLEN.read();
}

void compute_output::thread_m_axi_out_V_AWLOCK() {
    m_axi_out_V_AWLOCK = grp_store_output_fu_702_m_axi_out_V_AWLOCK.read();
}

void compute_output::thread_m_axi_out_V_AWPROT() {
    m_axi_out_V_AWPROT = grp_store_output_fu_702_m_axi_out_V_AWPROT.read();
}

void compute_output::thread_m_axi_out_V_AWQOS() {
    m_axi_out_V_AWQOS = grp_store_output_fu_702_m_axi_out_V_AWQOS.read();
}

void compute_output::thread_m_axi_out_V_AWREGION() {
    m_axi_out_V_AWREGION = grp_store_output_fu_702_m_axi_out_V_AWREGION.read();
}

void compute_output::thread_m_axi_out_V_AWSIZE() {
    m_axi_out_V_AWSIZE = grp_store_output_fu_702_m_axi_out_V_AWSIZE.read();
}

void compute_output::thread_m_axi_out_V_AWUSER() {
    m_axi_out_V_AWUSER = grp_store_output_fu_702_m_axi_out_V_AWUSER.read();
}

void compute_output::thread_m_axi_out_V_AWVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        m_axi_out_V_AWVALID = grp_store_output_fu_702_m_axi_out_V_AWVALID.read();
    } else {
        m_axi_out_V_AWVALID = ap_const_logic_0;
    }
}

void compute_output::thread_m_axi_out_V_BREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        m_axi_out_V_BREADY = grp_store_output_fu_702_m_axi_out_V_BREADY.read();
    } else {
        m_axi_out_V_BREADY = ap_const_logic_0;
    }
}

void compute_output::thread_m_axi_out_V_RREADY() {
    m_axi_out_V_RREADY = ap_const_logic_0;
}

void compute_output::thread_m_axi_out_V_WDATA() {
    m_axi_out_V_WDATA = grp_store_output_fu_702_m_axi_out_V_WDATA.read();
}

void compute_output::thread_m_axi_out_V_WID() {
    m_axi_out_V_WID = grp_store_output_fu_702_m_axi_out_V_WID.read();
}

void compute_output::thread_m_axi_out_V_WLAST() {
    m_axi_out_V_WLAST = grp_store_output_fu_702_m_axi_out_V_WLAST.read();
}

void compute_output::thread_m_axi_out_V_WSTRB() {
    m_axi_out_V_WSTRB = grp_store_output_fu_702_m_axi_out_V_WSTRB.read();
}

void compute_output::thread_m_axi_out_V_WUSER() {
    m_axi_out_V_WUSER = grp_store_output_fu_702_m_axi_out_V_WUSER.read();
}

void compute_output::thread_m_axi_out_V_WVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        m_axi_out_V_WVALID = grp_store_output_fu_702_m_axi_out_V_WVALID.read();
    } else {
        m_axi_out_V_WVALID = ap_const_logic_0;
    }
}

void compute_output::thread_m_axi_weight_V_ARADDR() {
    m_axi_weight_V_ARADDR = grp_load_weight_fu_714_m_axi_weight_V_ARADDR.read();
}

void compute_output::thread_m_axi_weight_V_ARBURST() {
    m_axi_weight_V_ARBURST = grp_load_weight_fu_714_m_axi_weight_V_ARBURST.read();
}

void compute_output::thread_m_axi_weight_V_ARCACHE() {
    m_axi_weight_V_ARCACHE = grp_load_weight_fu_714_m_axi_weight_V_ARCACHE.read();
}

void compute_output::thread_m_axi_weight_V_ARID() {
    m_axi_weight_V_ARID = grp_load_weight_fu_714_m_axi_weight_V_ARID.read();
}

void compute_output::thread_m_axi_weight_V_ARLEN() {
    m_axi_weight_V_ARLEN = grp_load_weight_fu_714_m_axi_weight_V_ARLEN.read();
}

void compute_output::thread_m_axi_weight_V_ARLOCK() {
    m_axi_weight_V_ARLOCK = grp_load_weight_fu_714_m_axi_weight_V_ARLOCK.read();
}

void compute_output::thread_m_axi_weight_V_ARPROT() {
    m_axi_weight_V_ARPROT = grp_load_weight_fu_714_m_axi_weight_V_ARPROT.read();
}

void compute_output::thread_m_axi_weight_V_ARQOS() {
    m_axi_weight_V_ARQOS = grp_load_weight_fu_714_m_axi_weight_V_ARQOS.read();
}

void compute_output::thread_m_axi_weight_V_ARREGION() {
    m_axi_weight_V_ARREGION = grp_load_weight_fu_714_m_axi_weight_V_ARREGION.read();
}

void compute_output::thread_m_axi_weight_V_ARSIZE() {
    m_axi_weight_V_ARSIZE = grp_load_weight_fu_714_m_axi_weight_V_ARSIZE.read();
}

void compute_output::thread_m_axi_weight_V_ARUSER() {
    m_axi_weight_V_ARUSER = grp_load_weight_fu_714_m_axi_weight_V_ARUSER.read();
}

void compute_output::thread_m_axi_weight_V_ARVALID() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_732_p3.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        m_axi_weight_V_ARVALID = grp_load_weight_fu_714_m_axi_weight_V_ARVALID.read();
    } else {
        m_axi_weight_V_ARVALID = ap_const_logic_0;
    }
}

void compute_output::thread_m_axi_weight_V_AWADDR() {
    m_axi_weight_V_AWADDR = ap_const_lv32_0;
}

void compute_output::thread_m_axi_weight_V_AWBURST() {
    m_axi_weight_V_AWBURST = ap_const_lv2_0;
}

void compute_output::thread_m_axi_weight_V_AWCACHE() {
    m_axi_weight_V_AWCACHE = ap_const_lv4_0;
}

void compute_output::thread_m_axi_weight_V_AWID() {
    m_axi_weight_V_AWID = ap_const_lv1_0;
}

void compute_output::thread_m_axi_weight_V_AWLEN() {
    m_axi_weight_V_AWLEN = ap_const_lv32_0;
}

void compute_output::thread_m_axi_weight_V_AWLOCK() {
    m_axi_weight_V_AWLOCK = ap_const_lv2_0;
}

void compute_output::thread_m_axi_weight_V_AWPROT() {
    m_axi_weight_V_AWPROT = ap_const_lv3_0;
}

void compute_output::thread_m_axi_weight_V_AWQOS() {
    m_axi_weight_V_AWQOS = ap_const_lv4_0;
}

void compute_output::thread_m_axi_weight_V_AWREGION() {
    m_axi_weight_V_AWREGION = ap_const_lv4_0;
}

void compute_output::thread_m_axi_weight_V_AWSIZE() {
    m_axi_weight_V_AWSIZE = ap_const_lv3_0;
}

void compute_output::thread_m_axi_weight_V_AWUSER() {
    m_axi_weight_V_AWUSER = ap_const_lv1_0;
}

void compute_output::thread_m_axi_weight_V_AWVALID() {
    m_axi_weight_V_AWVALID = ap_const_logic_0;
}

void compute_output::thread_m_axi_weight_V_BREADY() {
    m_axi_weight_V_BREADY = ap_const_logic_0;
}

void compute_output::thread_m_axi_weight_V_RREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_732_p3.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        m_axi_weight_V_RREADY = grp_load_weight_fu_714_m_axi_weight_V_RREADY.read();
    } else {
        m_axi_weight_V_RREADY = ap_const_logic_0;
    }
}

void compute_output::thread_m_axi_weight_V_WDATA() {
    m_axi_weight_V_WDATA = ap_const_lv16_0;
}

void compute_output::thread_m_axi_weight_V_WID() {
    m_axi_weight_V_WID = ap_const_lv1_0;
}

void compute_output::thread_m_axi_weight_V_WLAST() {
    m_axi_weight_V_WLAST = ap_const_logic_0;
}

void compute_output::thread_m_axi_weight_V_WSTRB() {
    m_axi_weight_V_WSTRB = ap_const_lv2_0;
}

void compute_output::thread_m_axi_weight_V_WUSER() {
    m_axi_weight_V_WUSER = ap_const_lv1_0;
}

void compute_output::thread_m_axi_weight_V_WVALID() {
    m_axi_weight_V_WVALID = ap_const_logic_0;
}

void compute_output::thread_tmp_fu_732_p3() {
    tmp_fu_732_p3 = ch_0_reg_612.read().range(6, 6);
}

void compute_output::thread_trunc_ln124_1_fu_728_p1() {
    trunc_ln124_1_fu_728_p1 = col.read().range(16-1, 0);
}

void compute_output::thread_trunc_ln124_fu_724_p1() {
    trunc_ln124_fu_724_p1 = row.read().range(16-1, 0);
}

void compute_output::thread_wt_buff_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        wt_buff_V_address0 = grp_load_weight_fu_714_wt_buff_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        wt_buff_V_address0 = grp_compute4_fu_624_wt_buff_V_address0.read();
    } else {
        wt_buff_V_address0 =  (sc_lv<12>) ("XXXXXXXXXXXX");
    }
}

void compute_output::thread_wt_buff_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        wt_buff_V_ce0 = grp_load_weight_fu_714_wt_buff_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        wt_buff_V_ce0 = grp_compute4_fu_624_wt_buff_V_ce0.read();
    } else {
        wt_buff_V_ce0 = ap_const_logic_0;
    }
}

void compute_output::thread_wt_buff_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        wt_buff_V_ce1 = grp_compute4_fu_624_wt_buff_V_ce1.read();
    } else {
        wt_buff_V_ce1 = ap_const_logic_0;
    }
}

void compute_output::thread_wt_buff_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        wt_buff_V_we0 = grp_load_weight_fu_714_wt_buff_V_we0.read();
    } else {
        wt_buff_V_we0 = ap_const_logic_0;
    }
}

void compute_output::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_732_p3.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(grp_load_weight_fu_714_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(grp_compute4_fu_624_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(grp_store_output_fu_702_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

}

