// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _load_weight_HH_
#define _load_weight_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "conv_mac_muladd_7cud.h"

namespace ap_rtl {

struct load_weight : public sc_module {
    // Port declarations 57
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > m_axi_weight_V_AWVALID;
    sc_in< sc_logic > m_axi_weight_V_AWREADY;
    sc_out< sc_lv<32> > m_axi_weight_V_AWADDR;
    sc_out< sc_lv<1> > m_axi_weight_V_AWID;
    sc_out< sc_lv<32> > m_axi_weight_V_AWLEN;
    sc_out< sc_lv<3> > m_axi_weight_V_AWSIZE;
    sc_out< sc_lv<2> > m_axi_weight_V_AWBURST;
    sc_out< sc_lv<2> > m_axi_weight_V_AWLOCK;
    sc_out< sc_lv<4> > m_axi_weight_V_AWCACHE;
    sc_out< sc_lv<3> > m_axi_weight_V_AWPROT;
    sc_out< sc_lv<4> > m_axi_weight_V_AWQOS;
    sc_out< sc_lv<4> > m_axi_weight_V_AWREGION;
    sc_out< sc_lv<1> > m_axi_weight_V_AWUSER;
    sc_out< sc_logic > m_axi_weight_V_WVALID;
    sc_in< sc_logic > m_axi_weight_V_WREADY;
    sc_out< sc_lv<16> > m_axi_weight_V_WDATA;
    sc_out< sc_lv<2> > m_axi_weight_V_WSTRB;
    sc_out< sc_logic > m_axi_weight_V_WLAST;
    sc_out< sc_lv<1> > m_axi_weight_V_WID;
    sc_out< sc_lv<1> > m_axi_weight_V_WUSER;
    sc_out< sc_logic > m_axi_weight_V_ARVALID;
    sc_in< sc_logic > m_axi_weight_V_ARREADY;
    sc_out< sc_lv<32> > m_axi_weight_V_ARADDR;
    sc_out< sc_lv<1> > m_axi_weight_V_ARID;
    sc_out< sc_lv<32> > m_axi_weight_V_ARLEN;
    sc_out< sc_lv<3> > m_axi_weight_V_ARSIZE;
    sc_out< sc_lv<2> > m_axi_weight_V_ARBURST;
    sc_out< sc_lv<2> > m_axi_weight_V_ARLOCK;
    sc_out< sc_lv<4> > m_axi_weight_V_ARCACHE;
    sc_out< sc_lv<3> > m_axi_weight_V_ARPROT;
    sc_out< sc_lv<4> > m_axi_weight_V_ARQOS;
    sc_out< sc_lv<4> > m_axi_weight_V_ARREGION;
    sc_out< sc_lv<1> > m_axi_weight_V_ARUSER;
    sc_in< sc_logic > m_axi_weight_V_RVALID;
    sc_out< sc_logic > m_axi_weight_V_RREADY;
    sc_in< sc_lv<16> > m_axi_weight_V_RDATA;
    sc_in< sc_logic > m_axi_weight_V_RLAST;
    sc_in< sc_lv<1> > m_axi_weight_V_RID;
    sc_in< sc_lv<1> > m_axi_weight_V_RUSER;
    sc_in< sc_lv<2> > m_axi_weight_V_RRESP;
    sc_in< sc_logic > m_axi_weight_V_BVALID;
    sc_out< sc_logic > m_axi_weight_V_BREADY;
    sc_in< sc_lv<2> > m_axi_weight_V_BRESP;
    sc_in< sc_lv<1> > m_axi_weight_V_BID;
    sc_in< sc_lv<1> > m_axi_weight_V_BUSER;
    sc_in< sc_lv<31> > weight_V_offset;
    sc_out< sc_lv<12> > wt_buff_V_address0;
    sc_out< sc_logic > wt_buff_V_ce0;
    sc_out< sc_logic > wt_buff_V_we0;
    sc_out< sc_lv<16> > wt_buff_V_d0;
    sc_in< sc_lv<7> > m;


    // Module declarations
    load_weight(sc_module_name name);
    SC_HAS_PROCESS(load_weight);

    ~load_weight();

    sc_trace_file* mVcdFile;

    conv_mac_muladd_7cud<1,1,7,9,31,32>* conv_mac_muladd_7cud_U14;
    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > weight_V_blk_n_AR;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > weight_V_blk_n_R;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > icmp_ln49_reg_162;
    sc_signal< sc_lv<12> > phi_ln49_reg_101;
    sc_signal< sc_lv<12> > phi_ln49_reg_101_pp0_iter1_reg;
    sc_signal< bool > ap_block_state9_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state11_pp0_stage0_iter2;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<32> > weight_V_addr_reg_156;
    sc_signal< sc_lv<1> > icmp_ln49_fu_130_p2;
    sc_signal< sc_lv<1> > icmp_ln49_reg_162_pp0_iter1_reg;
    sc_signal< sc_lv<12> > add_ln49_fu_136_p2;
    sc_signal< sc_lv<12> > add_ln49_reg_166;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<16> > weight_V_addr_read_reg_171;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state9;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<12> > ap_phi_mux_phi_ln49_phi_fu_105_p4;
    sc_signal< sc_lv<64> > zext_ln49_2_fu_142_p1;
    sc_signal< sc_lv<64> > zext_ln49_1_fu_121_p1;
    sc_signal< sc_lv<32> > grp_fu_147_p3;
    sc_signal< sc_lv<7> > grp_fu_147_p0;
    sc_signal< sc_lv<9> > grp_fu_147_p1;
    sc_signal< sc_lv<31> > grp_fu_147_p2;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_lv<16> > grp_fu_147_p00;
    sc_signal< sc_lv<32> > grp_fu_147_p20;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_fsm_state1;
    static const sc_lv<10> ap_ST_fsm_state2;
    static const sc_lv<10> ap_ST_fsm_state3;
    static const sc_lv<10> ap_ST_fsm_state4;
    static const sc_lv<10> ap_ST_fsm_state5;
    static const sc_lv<10> ap_ST_fsm_state6;
    static const sc_lv<10> ap_ST_fsm_state7;
    static const sc_lv<10> ap_ST_fsm_state8;
    static const sc_lv<10> ap_ST_fsm_pp0_stage0;
    static const sc_lv<10> ap_ST_fsm_state12;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_8;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<32> ap_const_lv32_930;
    static const sc_lv<12> ap_const_lv12_930;
    static const sc_lv<12> ap_const_lv12_1;
    static const sc_lv<16> ap_const_lv16_93;
    static const sc_lv<32> ap_const_lv32_9;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln49_fu_136_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state8();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state10_pp0_stage0_iter1();
    void thread_ap_block_state11_pp0_stage0_iter2();
    void thread_ap_block_state9_pp0_stage0_iter0();
    void thread_ap_condition_pp0_exit_iter0_state9();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_phi_ln49_phi_fu_105_p4();
    void thread_ap_ready();
    void thread_grp_fu_147_p0();
    void thread_grp_fu_147_p00();
    void thread_grp_fu_147_p1();
    void thread_grp_fu_147_p2();
    void thread_grp_fu_147_p20();
    void thread_icmp_ln49_fu_130_p2();
    void thread_m_axi_weight_V_ARADDR();
    void thread_m_axi_weight_V_ARBURST();
    void thread_m_axi_weight_V_ARCACHE();
    void thread_m_axi_weight_V_ARID();
    void thread_m_axi_weight_V_ARLEN();
    void thread_m_axi_weight_V_ARLOCK();
    void thread_m_axi_weight_V_ARPROT();
    void thread_m_axi_weight_V_ARQOS();
    void thread_m_axi_weight_V_ARREGION();
    void thread_m_axi_weight_V_ARSIZE();
    void thread_m_axi_weight_V_ARUSER();
    void thread_m_axi_weight_V_ARVALID();
    void thread_m_axi_weight_V_AWADDR();
    void thread_m_axi_weight_V_AWBURST();
    void thread_m_axi_weight_V_AWCACHE();
    void thread_m_axi_weight_V_AWID();
    void thread_m_axi_weight_V_AWLEN();
    void thread_m_axi_weight_V_AWLOCK();
    void thread_m_axi_weight_V_AWPROT();
    void thread_m_axi_weight_V_AWQOS();
    void thread_m_axi_weight_V_AWREGION();
    void thread_m_axi_weight_V_AWSIZE();
    void thread_m_axi_weight_V_AWUSER();
    void thread_m_axi_weight_V_AWVALID();
    void thread_m_axi_weight_V_BREADY();
    void thread_m_axi_weight_V_RREADY();
    void thread_m_axi_weight_V_WDATA();
    void thread_m_axi_weight_V_WID();
    void thread_m_axi_weight_V_WLAST();
    void thread_m_axi_weight_V_WSTRB();
    void thread_m_axi_weight_V_WUSER();
    void thread_m_axi_weight_V_WVALID();
    void thread_weight_V_blk_n_AR();
    void thread_weight_V_blk_n_R();
    void thread_wt_buff_V_address0();
    void thread_wt_buff_V_ce0();
    void thread_wt_buff_V_d0();
    void thread_wt_buff_V_we0();
    void thread_zext_ln49_1_fu_121_p1();
    void thread_zext_ln49_2_fu_142_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
